package com.fullstory.guidesandsurveys

import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReadableMap
import com.facebook.react.module.annotations.ReactModule

// NativeGuidesAndSurveysSpec is generated by React Native codegen from
// src/NativeGuidesAndSurveys.ts. This file is only compiled when newArchEnabled=true,
// at which point the com.facebook.react plugin has already run codegen.
@ReactModule(name = RNGuidesAndSurveysModuleImpl.NAME)
class RNGuidesAndSurveysModule(private val reactContext: ReactApplicationContext) :
    NativeGuidesAndSurveysSpec(reactContext) {

    override fun getName(): String = RNGuidesAndSurveysModuleImpl.NAME

    override fun initialize(
        orgId: String,
        environment: String,
        config: ReadableMap?,
        promise: Promise,
    ) {
        RNGuidesAndSurveysModuleImpl.initialize(
            reactContext, orgId, environment, config, promise
        )
    }

    override fun identify(userId: String, promise: Promise) {
        RNGuidesAndSurveysModuleImpl.identify(userId, promise)
    }

    override fun anonymize(promise: Promise) {
        RNGuidesAndSurveysModuleImpl.anonymize(promise)
    }

    override fun showSurvey(surveyId: String?, promise: Promise) {
        RNGuidesAndSurveysModuleImpl.showSurvey(surveyId, promise)
    }

    override fun getAreSurveysDisabled(promise: Promise) {
        RNGuidesAndSurveysModuleImpl.getAreSurveysDisabled(promise)
    }

    override fun setSessionId(sessionId: String, promise: Promise) {
        RNGuidesAndSurveysModuleImpl.setSessionId(sessionId, promise)
    }

    override fun setCurrentScreen(screenName: String?, promise: Promise) {
        RNGuidesAndSurveysModuleImpl.setCurrentScreen(screenName, promise)
    }
}
