package com.fullstory.guidesandsurveys

import android.os.Handler
import android.os.Looper
import androidx.activity.ComponentActivity
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactMethod
import com.facebook.react.module.annotations.ReactModule
import com.fullstory.surveys.sdk.Environment
import com.fullstory.surveys.sdk.SurveysSDK

// NativeGuidesAndSurveysSpec is the abstract class generated by React Native codegen from
// src/NativeGuidesAndSurveys.ts. It extends ReactContextBaseJavaModule, so this class works
// on both old arch (via @ReactMethod reflection) and new arch (via the TurboModule system).
@ReactModule(name = RNGuidesAndSurveysModule.NAME)
class RNGuidesAndSurveysModule(reactContext: ReactApplicationContext) :
    NativeGuidesAndSurveysSpec(reactContext) {

    override fun getName(): String = NAME

    private fun environmentFrom(string: String): Environment = when (string.lowercase()) {
        "staging"     -> Environment.STAGING
        "development" -> Environment.DEVELOPMENT
        // iOS uses "playpen" for the dev environment
        "playpen"     -> Environment.DEVELOPMENT
        else          -> Environment.PRODUCTION
    }

    private fun onMain(block: () -> Unit) =
        Handler(Looper.getMainLooper()).post(block)

    @ReactMethod
    override fun initialize(orgId: String, environment: String, userId: String, promise: Promise) {
        onMain {
            try {
                SurveysSDK.initialize(
                    context      = reactApplicationContext,
                    accountToken = orgId,
                    orgId        = orgId,
                    userId       = userId,
                    environment  = environmentFrom(environment)
                )
                val activity = reactApplicationContext.currentActivity as? ComponentActivity
                if (activity != null) {
                    SurveyHostInstaller.install(activity)
                }
                promise.resolve(null)
            } catch (e: Exception) {
                promise.reject("INIT_ERROR", e.message, e)
            }
        }
    }

    @ReactMethod
    override fun identify(userId: String, promise: Promise) {
        onMain {
            try {
                SurveysSDK.identify(userId)
                promise.resolve(null)
            } catch (e: Exception) {
                promise.reject("IDENTIFY_ERROR", e.message, e)
            }
        }
    }

    @ReactMethod
    override fun showSurvey(surveyId: String?, promise: Promise) {
        onMain {
            try {
                SurveysSDK.showSurvey(surveyId)
                promise.resolve(null)
            } catch (e: Exception) {
                promise.reject("SHOW_SURVEY_ERROR", e.message, e)
            }
        }
    }

    @ReactMethod
    override fun getAreSurveysDisabled(promise: Promise) {
        promise.resolve(SurveysSDK.areSurveysDisabled())
    }

    companion object {
        const val NAME = "RNGuidesAndSurveys"
    }
}
